export const CREATE_NEW_NOTE = 'CREATE_NEW_NOTE';
export const SELECT_NOTE = 'SELECT_NOTE';
export const SAVE_NOTE = 'SAVE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const SELECT_SETTING = 'SELECT_SETTING';
export const SELECT_SETTING_ALL = 'SELECT_SETTING_ALL';
export const SELECT_CHAPTER = 'SELECT_CHAPTER';
export const SHOW_NAV_MENU = 'SHOW_NAV_MENU';


export const CREATE_NEW_CHPATER = 'CREATE_NEW_CHPATER';
export const DELETE_CHAPTER = 'DELETE_CHAPTER';
